name: commons-workflows-main

on:
  workflow_call:
    inputs:
      GPR_USER:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
        env:
          GPR_USER: ${{ inputs.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: test
