name: commons-workflows-release

on:
  workflow_call:
    inputs:
      GPR_USER:
        required: true
        type: string

jobs:
  main:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      GPR_USER: ${{ inputs.GPR_USER }}

  release:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: echo "RELEASE_VERSION=$(echo ${{ github.ref_name }} | awk  -F/ '{print $NF}')" >> $GITHUB_ENV

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -Pversion=${{ env.RELEASE_VERSION }}
            publish
        env:
          GPR_USER: ${{ inputs.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}
